[book]
title = "mdBook Pikchr"
authors = ["Konstantin Podsvirov <konstantin@podsvirov.pro>"]
multilingual = false
language = "en"
src = "."

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/podsvirov/mdbook-pikchr"
edit-url-template = "https://github.com/podsvirov/mdbook-pikchr/edit/master/{path}"

[preprocessor.pikchr]
command = "target/release/mdbook-pikchr"
